### PR TITLE
Support for tick data

### PR DESCRIPTION
**Pull request by freedumb2000**
Added support for tick data among other things. Below is the contents of the change log.

- add support for multiple datastreams in parallel for any combination of symbols and timeframes independently of the timeframe and symbol of the attached chart
- add support for tick data
- add support for direct download as CSV files
- add one automatic retry binding to sockets. When running under Wine in Linux, sockets will be blocked for 60 seconds if closed uncleanly. This can happen if the client is still connected while the EA gets reloaded.
- skip re-initialization on chart timeframe change

This PR offers functionality which is required for PR https://github.com/khramkov/Backtrader-MQL5-API/pull/4

### CODE REVIEW

**Comment by khramkov** [comment]
Hi, happy New Year.  I'll check the code today.

**Comment by freedumb2000** [comment]
Great, a happy new years to you too :)

**Comment by freedumb2000** [comment]
I added a workaround for the problem that ports are locked when re-initializing the Expert when running MT5 unter Wine.
I think the issue relates to this: https://forum.winehq.org/viewtopic.php?t=22758
The workaround simply waits for 65 seconds before attempting again.

**Comment by freedumb2000** [comment]
I found some problem getting multiple symbols with diff. data frames. I will .open a new PR once it is fixed.

**Comment by khramkov** [comment]
Hi. U did a great job! Explain me this idea, please
if (reason != REASON_CHARTCHANGE)

**Comment by khramkov** [comment]
Hi.
I don't understand your idea about script denit. The script can change Symbol and TF without denit. Can you explain me your goal, please?

**Comment by freedumb2000** [comment]
> Hi.
> I don't understand your idea about script denit. The script can change Symbol and TF without denit. Can you explain me your goal, please?

When the users changes for example the time  frame of a chart that the EA script is attached to, MT5 will call OnDeInit() and OnInit(). This would normally unregister and re-register the ports for ZMQ. The EA relies on nothing displayed on the chart to function, it is independent from the symbol or timeframe displayed. So a re-load of the script is unnecessary thus it is skipped when the reason for calling OnDeInit() is a change of the chart the EA is attached to.

**Comment by freedumb2000** [comment]
This is pretty much ready to get pulled now, let me know if everything looks fine.

**Comment by khramkov** [comment]
U did a great job. I dreamed about what u did.) 
I apologize for the long time studying the code, i had catastrophic load. I am working over docs now. 
Would be glad to see you as collaborator.

**Comment by khramkov** [comment]
1. Updated docs.
2. Updated `ResetSubscriptions`. It was sending error message always.
```
void ResetSubscriptions(CJAVal &dataObject){

   ArrayFree(chartSymbols);
   chartSymbolCount=0;
   ArrayFree(chartSymbolSettings);
   
   if(ArraySize(chartSymbols)!=0 ||ArraySize(chartSymbolSettings)!=0){
   // TODO Implement propery error codes and descriptions
   ActionDoneOrError(65540,  __FUNCTION__);
   }
   else ActionDoneOrError(ERR_SUCCESS, __FUNCTION__);  
}
```
3. Refactored `oninit`. Binding attempts was added.  
```
int OnInit(){
  /* Bindinig ZMQ ports on init */
  
  // Skip reloading of the EA script when the reason to reload is a chart timeframe change
  if (deInitReason != REASON_CHARTCHANGE){
  
    EventSetMillisecondTimer(1);

    int bindSocketsDelay = 65; // Seconds to wait if binding of sockets fails.
    int bindAttemtps = 2; // Number of binding attemtps 
   
    Print("Binding sockets...");
   
    for(int i=0;i<bindAttemtps+1;i++){
      if (BindSockets()) return(INIT_SUCCEEDED);
      else {
         Print("Binding sockets failed. Waiting ", bindSocketsDelay, " seconds to try again...");
         Sleep(bindSocketsDelay*1000);
      }     
    }
    
    Print("Binding of sockets failed permanently.");
    return(INIT_FAILED);
  }

  return(INIT_SUCCEEDED);
}
```

**Pull request merged**
